services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: goodbooks-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017
      DB_NAME: goodbooks
      API_KEY: dev-key
    depends_on:
      - mongo

volumes:
  mongo-data:
